### ISSUE TITLE
get-twin does not work

### ISSUE THREAD

**Issue by lucarv** [Azure/iothub-explorer#11]
I have created devices using explorer and then jut run a get-twin and it crashes all the time as below....

ekskog-2:IoT-Hub-LwM2M-Bridge epkloc$ iothub-explorer get-twin kthsim001
/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/node_modules/colors/lib/extendStringPrototype.js:70
      'indexOf', 'lastIndexof', 'length', 'localeCompare', 'match', 'replace', 'search', 'slice', 'split', 'substring',
                                                              ^

RangeError: Maximum call stack size exceeded
    at Object.stylize (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/node_modules/colors/lib/colors.js:55:33)
    at String.green (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/node_modules/colors/lib/extendStringPrototype.js:58:21)
    at addColorToData (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:81:20)
    at Object.render (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:101:45)
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:159:24
    at Array.forEach (native)
    at Object.render (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:144:38)
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:166:19
    at Array.forEach (native)
    at Object.render (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:144:38)
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:166:19
    at Array.forEach (native)
    at Object.render (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:144:38)
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:166:19
    at Array.forEach (native)
    at Object.render (/usr/local/lib/node_modules/iothub-explorer/node_modules/prettyjson/lib/prettyjson.js:144:38)

**Comment by lucarv** [comment]
i was using 2.0.0, which i assume it is newer than 1.1.7
ekskog-2:~ epkloc$ iothub-explorer --version
2.0.0

i have put 1.1.7 back and it works now...

**Comment by pierreca** [comment]
Oh my, yes, sorry for the confusion. we screwed up the numbering that time a while ago and should have deprecated that version of the package... 1.1.7 is the latest. Closing this issue but I'm definitely going to look into cleaning that up a little more.
