### ISSUE TITLE
get-twin crashes in prettyjson

### ISSUE THREAD

**Issue by olivierbloch** [Azure/iothub-explorer#2]
When using get-twin without the -r option, I am getting the below error. No issue when using -r
Traces below

C:\Users\obloch>iothub-explorer get-twin -r nodedevice
{"deviceId":"nodedevice","etag":"AAAAAAAAAAM=","properties":{"desired":{"fan":"off","$metadata":{"$lastUpdated":"2016-12-07T08:29:30.9430446Z","$lastUpdatedVersion":3,"fan":{"$lastUpdated":"2016-12-07T08:29:30.9430446Z","$lastUpdatedVersion":3}},"$version":3},"reported":{"firmwareVersion":"1.2.1","weather":{"temperature":72,"humidity":17},"$metadata":{"$lastUpdated":"2016-12-07T08:27:47.6202203Z","firmwareVersion":{"$lastUpdated":"2016-12-07T08:27:47.6202203Z"},"weather":{"$lastUpdated":"2016-12-07T08:27:47.6202203Z","temperature":{"$lastUpdated":"2016-12-07T08:27:47.6202203Z"},"humidity":{"$lastUpdated":"2016-12-07T08:27:47.6202203Z"}}},"$version":2}},"tags":{}}

C:\Users\obloch>iothub-explorer get-twin nodedevice
C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\node_modules\colors\lib\colors.js:112
    str = code.open + str.replace(code.closeRe, code.open) + code.close;
                          ^

RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Function.applyStyle (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\node_modules\colors\lib\colors.js:112:27)
    at Object.builder (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\node_modules\colors\lib\colors.js:68:23)
    at addColorToData (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:46:19)
    at renderToArray (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:78:41)
    at C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:161:14
    at Array.forEach (native)
    at renderToArray (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:145:36)
    at C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:169:9
    at Array.forEach (native)
    at renderToArray (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:145:36)
    at C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:169:9
    at Array.forEach (native)
    at renderToArray (C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:145:36)
    at C:\Users\obloch\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\prettyjson\lib\prettyjson.js:169:9

**Comment by pierreca** [comment]
Looks like prettyjson tries to serialize properties starting with `_` and there's one in the twin object that isn't serializable. Fix is in code review and should be out with the next release.

**Comment by pierreca** [comment]
Closing as the fix is checked in - will be released as npm package in the next couple of days
