### ISSUE TITLE
Can't monitor-events

### ISSUE THREAD

**Issue by lmussier** [Azure/iothub-explorer#25]
# Context
- **OS and version used:** Ubuntu 16.04 LTS
- **Node.js version:** 4.2.6
- **npm version:** 3.5.2
- **iothub-explorer:** 1.1.14

# Description of the issue:
When trying to use the monitor-events feature like described here : https://github.com/Azure/iothub-explorer#working-with-devices we get an exception.

# Console log of the issue:
```
lmussier@lmussier-virtual-machine:~/workspace/build-agent/iothubAgent-build-folder/src/iothubAgent-build/Linux/bin$ iothub-explorer monitor-events Ludo --login 'XXXXXXXXXXXXXXXXX'

Monitoring events from device Ludo...

/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:27
    if (!config[prop]) throw makeError(prop);
                       ^
ArgumentError: config is missing property keyName
    at EventHubClient.makeError (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:23:12)
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:27:30
    at Array.forEach (native)
    at new EventHubClient (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:26:38)
    at Function.EventHubClient.fromConnectionString (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:95:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/iothub-explorer/iothub-explorer-monitor-events.js:42:32)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by pierreca** [comment]
@lmussier What connection string are you using? you should be using the one for either the `iothubowner` or `service` policy, not a device connection string.

The device connection (DO NOT use this one) string looks like that:
```
HostName=<...>;DeviceId=<...>;SharedAccessKey=<...>
```

The iothubowner or service connection string (DO use either one or the other) looks like that:
```
HostName=<...>;SharedAccessKeyName=<...>;SharedAccessKey=<...>
```

From the error it looks like you're missing the `SharedAccessKeyName` parameter. 
Also another thing you may want to check is using quotes or double-quotes around the connection string depending on your shell: you don't want the `;` characters in the connection string to be interpreted as the end of the command.

Please let us know if that helps!

**Comment by lmussier** [comment]
@pierreca ... my bad, I use the device connection string.
Thanks.
