### ISSUE TITLE
iothub-explorer monitor-events --login ... doesn't work

### ISSUE THREAD

**Issue by obastemur** [Azure/iothub-explorer#46]
command  :

```
> iothub-explorer monitor-events --login "..."
```

output below;

```
Monitoring events from all devices...

/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:27
    if (!config[prop]) throw makeError(prop);
                       ^
ArgumentError: config is missing property keyName
    at makeError (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:23:12)
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:27:30
    at Array.forEach (<anonymous>)
    at new EventHubClient (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:26:38)
    at Function.EventHubClient.fromConnectionString (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-event-hubs/lib/client.js:95:10)
    at monitorEvents (/usr/local/lib/node_modules/iothub-explorer/iothub-explorer-monitor-events.js:67:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/iothub-explorer/iothub-explorer-monitor-events.js:152:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

**Comment by obastemur** [comment]
Besides; I tried adding device id right after `monitor-events`.. this time it failed again but said my connection string doesn't have `sharedAccessKeyName`. Just checked the portal and iot hub connection string doesn't have such information.

**Comment by anthonyvercolano** [comment]
Well the other problem could be that you are using a device connection string instead of a hub connection string.

**Comment by anthonyvercolano** [comment]
You can find that in your shared access policies for the hub.

**Comment by obastemur** [comment]
That solved the issue. Thanks ;)
